// Catálogo de ejercicios con el reparto de trabajo por músculo: 1 = directo, 0,5 = indirecto.
// Conteo de volumen fraccional (Pelland et al. 2025). Nombres en español de España.

export const MUSCLES = [
  ['pecho', 'Pectoral'],
  ['espalda', 'Espalda'],
  ['trapecio', 'Trapecio'],
  ['delt_ant', 'Deltoides anterior'],
  ['delt_lat', 'Deltoides lateral'],
  ['delt_post', 'Deltoides posterior'],
  ['biceps', 'Bíceps'],
  ['triceps', 'Tríceps'],
  ['antebrazo', 'Antebrazo'],
  ['cuadriceps', 'Cuádriceps'],
  ['isquios', 'Isquiotibiales'],
  ['gluteos', 'Glúteos'],
  ['aductores', 'Aductores'],
  ['gemelos', 'Gemelos'],
  ['abdomen', 'Abdomen'],
  ['lumbar', 'Lumbar'],
];
export const MUSCLE_LABEL = Object.fromEntries(MUSCLES);

// [id, nombre, alias, músculos]
const RAW = [
  // ---------- pecho
  ['press_banca', 'Press banca con barra', ['press plano con barra', 'bench press', 'press banca'], { pecho: 1, triceps: 0.5, delt_ant: 0.5 }],
  ['press_banca_manc', 'Press banca con mancuernas', ['press plano con mancuernas'], { pecho: 1, triceps: 0.5, delt_ant: 0.5 }],
  ['press_incl_barra', 'Press inclinado con barra', ['press inclinado barra'], { pecho: 1, delt_ant: 0.5, triceps: 0.5 }],
  ['press_incl_manc', 'Press inclinado con mancuernas', ['press inclinado mancuernas'], { pecho: 1, delt_ant: 0.5, triceps: 0.5 }],
  ['press_incl_smith', 'Press inclinado en multipower', ['press inclinado smith', 'press inclinado multipower'], { pecho: 1, delt_ant: 0.5, triceps: 0.5 }],
  ['press_decl', 'Press declinado', [], { pecho: 1, triceps: 0.5 }],
  ['press_pecho_maq', 'Press de pecho en máquina', ['chest press', 'press en máquina'], { pecho: 1, triceps: 0.5, delt_ant: 0.5 }],
  ['aperturas_manc', 'Aperturas con mancuernas', ['flyes', 'aperturas'], { pecho: 1 }],
  ['aperturas_contractora', 'Aperturas en contractora', ['pec deck', 'contractora', 'peck deck'], { pecho: 1 }],
  ['cruce_poleas', 'Cruce de poleas', ['cruce de poleas altas', 'crossover'], { pecho: 1 }],
  ['cruce_poleas_bajas', 'Cruce de poleas bajas', [], { pecho: 1, delt_ant: 0.5 }],
  ['flexiones', 'Flexiones', ['push ups', 'flexiones de brazos'], { pecho: 1, triceps: 0.5, delt_ant: 0.5 }],
  ['flexiones_deficit', 'Flexiones en déficit', ['flexiones deficit'], { pecho: 1, triceps: 0.5, delt_ant: 0.5 }],
  ['fondos', 'Fondos en paralelas', ['fondos', 'dips'], { pecho: 1, triceps: 1, delt_ant: 0.5 }],
  // ---------- espalda
  ['dominadas', 'Dominadas', ['pull ups', 'dominadas pronas'], { espalda: 1, biceps: 0.5, delt_post: 0.5 }],
  ['dominadas_supinas', 'Dominadas supinas', ['chin ups'], { espalda: 1, biceps: 0.5 }],
  ['jalon_pecho', 'Jalón al pecho', ['jalón en polea alta', 'lat pulldown', 'jalon'], { espalda: 1, biceps: 0.5, delt_post: 0.5 }],
  ['jalon_neutro', 'Jalón con agarre neutro', ['jalón neutro'], { espalda: 1, biceps: 0.5 }],
  ['jalon_supino', 'Jalón supino', [], { espalda: 1, biceps: 0.5 }],
  ['jalon_unilateral', 'Jalón unilateral en polea alta', ['jalón a una mano', 'jalón neutro unilateral', 'jalón supino unilateral'], { espalda: 1, biceps: 0.5 }],
  ['remo_barra', 'Remo con barra', ['remo inclinado con barra', 'barbell row'], { espalda: 1, trapecio: 0.5, delt_post: 0.5, biceps: 0.5, lumbar: 0.5 }],
  ['remo_pendlay', 'Remo Pendlay', [], { espalda: 1, trapecio: 0.5, delt_post: 0.5, biceps: 0.5, lumbar: 0.5 }],
  ['remo_manc', 'Remo con mancuerna a una mano', ['remo mancuerna', 'remo a una mano'], { espalda: 1, delt_post: 0.5, biceps: 0.5 }],
  ['remo_manc_incl', 'Remo con mancuernas en banco inclinado', ['remo pecho apoyado', 'remo mancuernas banco inclinado', 'chest supported row'], { espalda: 1, delt_post: 0.5, trapecio: 0.5, biceps: 0.5 }],
  ['remo_polea_baja', 'Remo en polea baja', ['remo sentado en polea', 'remo gironda', 'seated row'], { espalda: 1, trapecio: 0.5, biceps: 0.5, delt_post: 0.5 }],
  ['remo_polea_unilateral', 'Remo en polea baja a una mano', ['remo polea baja a 1 brazo', 'remo polea baja supino a 1 brazo', 'remo sentado en polea baja a un brazo'], { espalda: 1, biceps: 0.5, delt_post: 0.5 }],
  ['remo_maquina', 'Remo en máquina', ['remo hammer', 'remo t'], { espalda: 1, trapecio: 0.5, biceps: 0.5, delt_post: 0.5 }],
  ['remo_meadows', 'Remo Meadows', ['meadows row'], { espalda: 1, delt_post: 0.5, biceps: 0.5 }],
  ['remo_t', 'Remo en T', ['t-bar row'], { espalda: 1, trapecio: 0.5, biceps: 0.5, delt_post: 0.5, lumbar: 0.5 }],
  ['pullover_polea', 'Pull-over en polea alta', ['pullover polea', 'pull over polea', 'pull-over polea alta unilateral'], { espalda: 1 }],
  ['pullover_manc', 'Pull-over con mancuerna', ['pullover'], { espalda: 1, pecho: 0.5 }],
  // ---------- trapecio / hombro posterior
  ['encogimientos_hombros', 'Encogimientos de hombros', ['shrugs', 'encogimientos con mancuernas', 'encogimientos con barra'], { trapecio: 1 }],
  ['retracciones_escapulares', 'Retracciones escapulares en polea', ['retracciones escapulares', 'retracción escapular'], { trapecio: 1, delt_post: 0.5 }],
  ['face_pull', 'Face pull', ['tirón a la cara'], { delt_post: 1, trapecio: 0.5 }],
  ['pajaros', 'Pájaros con mancuernas', ['pájaros', 'elevaciones posteriores', 'rear delt fly', 'pájaros banco inclinado', 'pájaros con mancuernas en banco inclinado'], { delt_post: 1, trapecio: 0.5 }],
  ['pajaros_maquina', 'Pájaros en máquina', ['contractora inversa', 'reverse pec deck'], { delt_post: 1, trapecio: 0.5 }],
  ['pajaros_polea', 'Pájaros en polea', ['cruce de poleas inverso'], { delt_post: 1 }],
  // ---------- hombro
  ['press_militar', 'Press militar con barra', ['press militar', 'overhead press', 'press de hombros con barra'], { delt_ant: 1, triceps: 0.5, delt_lat: 0.5 }],
  ['press_hombro_manc', 'Press de hombros con mancuernas', ['press militar mancuernas', 'press arnold'], { delt_ant: 1, triceps: 0.5, delt_lat: 0.5 }],
  ['press_hombro_maq', 'Press de hombros en máquina', [], { delt_ant: 1, triceps: 0.5, delt_lat: 0.5 }],
  ['elev_laterales', 'Elevaciones laterales con mancuernas', ['elevaciones laterales', 'lateral raises'], { delt_lat: 1 }],
  ['elev_laterales_polea', 'Elevaciones laterales en polea baja', ['elevaciones laterales polea', 'laterales en polea'], { delt_lat: 1 }],
  ['elev_laterales_maq', 'Elevaciones laterales en máquina', [], { delt_lat: 1 }],
  ['six_ways', '6 Ways', ['six ways', '6 ways'], { delt_lat: 1, delt_ant: 0.5 }],
  ['elev_frontales', 'Elevaciones frontales', ['frontales'], { delt_ant: 1 }],
  ['remo_menton', 'Remo al mentón', ['upright row'], { delt_lat: 1, trapecio: 0.5 }],
  // ---------- bíceps
  ['curl_barra', 'Curl con barra', ['curl de bíceps con barra', 'curl barra z'], { biceps: 1, antebrazo: 0.5 }],
  ['curl_manc', 'Curl con mancuernas', ['curl de bíceps'], { biceps: 1, antebrazo: 0.5 }],
  ['curl_alterno', 'Curl alterno con mancuernas', ['curl alterno'], { biceps: 1, antebrazo: 0.5 }],
  ['curl_incl', 'Curl con mancuernas en banco inclinado', ['curl inclinado', 'curl banco inclinado'], { biceps: 1 }],
  ['curl_martillo', 'Curl martillo', ['hammer curl'], { biceps: 1, antebrazo: 1 }],
  ['curl_predicador', 'Curl predicador', ['curl scott', 'curl predicador en máquina'], { biceps: 1 }],
  ['curl_polea', 'Curl en polea', ['curl polea baja', 'curl bayesian'], { biceps: 1 }],
  ['curl_concentrado', 'Curl concentrado', [], { biceps: 1 }],
  // ---------- tríceps
  ['ext_triceps_polea', 'Extensión de tríceps en polea', ['jalón de tríceps', 'pushdown', 'tríceps en polea'], { triceps: 1 }],
  ['ext_triceps_unilateral', 'Extensión de tríceps en polea a una mano', ['extensión tríceps cable unilateral', 'extensiones de tríceps con cable neutro unilateral'], { triceps: 1 }],
  ['ext_triceps_sobre_cabeza', 'Extensión de tríceps sobre la cabeza', ['extensión tras nuca', 'overhead extension'], { triceps: 1 }],
  ['press_frances', 'Press francés', ['press francés con barra z', 'press francés ez', 'skull crusher', 'press francés sentado ez trasnuca'], { triceps: 1 }],
  ['patada_triceps', 'Patada de tríceps', ['patada de tríceps en polea', 'kickback'], { triceps: 1 }],
  ['press_cerrado', 'Press banca agarre cerrado', ['press cerrado'], { triceps: 1, pecho: 0.5, delt_ant: 0.5 }],
  ['dirty_30', 'Dirty 30', ['dirty 30'], { triceps: 1 }],
  ['fondos_banco', 'Fondos en banco', [], { triceps: 1, pecho: 0.5 }],
  // ---------- antebrazo
  ['curl_muneca', 'Curl de muñeca', ['antebrazo'], { antebrazo: 1 }],
  // ---------- cuádriceps / piernas
  ['sentadilla', 'Sentadilla trasera', ['sentadilla', 'squat', 'sentadilla barra alta', 'sentadilla trasera barra alta'], { cuadriceps: 1, gluteos: 1, aductores: 0.5, lumbar: 0.5 }],
  ['sentadilla_multipower', 'Sentadilla en multipower', ['sentadilla smith', 'sentadilla trasera en mp', 'sentadilla trasera en mp barra alta', 'sentadilla mp'], { cuadriceps: 1, gluteos: 1, aductores: 0.5 }],
  ['sentadilla_frontal', 'Sentadilla frontal', ['front squat'], { cuadriceps: 1, gluteos: 0.5 }],
  ['sentadilla_hack', 'Sentadilla hack', ['hack squat', 'hack'], { cuadriceps: 1, gluteos: 0.5 }],
  ['sentadilla_bulgara', 'Sentadilla búlgara', ['bulgarian split squat', 'búlgara'], { cuadriceps: 1, gluteos: 1, aductores: 0.5 }],
  ['sentadilla_goblet', 'Sentadilla goblet', [], { cuadriceps: 1, gluteos: 0.5 }],
  ['zancadas', 'Zancadas', ['lunges', 'zancadas con mancuernas'], { cuadriceps: 1, gluteos: 1, aductores: 0.5 }],
  ['prensa', 'Prensa inclinada', ['prensa', 'prensa de piernas', 'leg press'], { cuadriceps: 1, gluteos: 0.5, aductores: 0.5 }],
  ['prensa_unilateral', 'Prensa inclinada a una pierna', ['prensa a una pierna', 'prensa inclinada a 1 pierna'], { cuadriceps: 1, gluteos: 0.5 }],
  ['extension_cuadriceps', 'Extensión de cuádriceps', ['extensiones de rodilla', 'extensiones de rodilla en máquina', 'leg extension', 'extensión de piernas'], { cuadriceps: 1 }],
  ['sissy', 'Sentadilla sissy', ['sissy squat'], { cuadriceps: 1 }],
  // ---------- isquios / glúteos
  ['peso_muerto', 'Peso muerto', ['deadlift', 'peso muerto convencional'], { isquios: 1, gluteos: 1, lumbar: 1, espalda: 0.5, trapecio: 0.5, cuadriceps: 0.5 }],
  ['peso_muerto_rumano', 'Peso muerto rumano con barra', ['peso muerto rumano', 'rdl', 'rumano'], { isquios: 1, gluteos: 1, lumbar: 0.5 }],
  ['peso_muerto_rumano_manc', 'Peso muerto rumano con mancuernas', [], { isquios: 1, gluteos: 1, lumbar: 0.5 }],
  ['peso_muerto_piernas_rigidas', 'Peso muerto con piernas rígidas', ['stiff leg deadlift'], { isquios: 1, gluteos: 0.5, lumbar: 0.5 }],
  ['buenos_dias', 'Buenos días', ['good morning'], { isquios: 1, lumbar: 1, gluteos: 0.5 }],
  ['curl_femoral_sentado', 'Curl femoral sentado', ['curl de isquios sentado', 'curl femoral', 'leg curl sentado'], { isquios: 1 }],
  ['curl_femoral_tumbado', 'Curl femoral tumbado', ['curl de isquios tumbado', 'leg curl tumbado'], { isquios: 1 }],
  ['curl_nordico', 'Curl nórdico', ['nordic curl'], { isquios: 1 }],
  ['hip_thrust', 'Hip thrust', ['empuje de cadera', 'hip thrust con barra'], { gluteos: 1, isquios: 0.5 }],
  ['puente_gluteo', 'Puente de glúteo', ['glute bridge'], { gluteos: 1, isquios: 0.5 }],
  ['patada_gluteo', 'Patada de glúteo en polea', ['patada de glúteo'], { gluteos: 1 }],
  ['abduccion_maq', 'Abducción de cadera en máquina', ['abductores', 'abducción'], { gluteos: 1 }],
  ['aduccion_maq', 'Aducción de cadera en máquina', ['aductores', 'aducción'], { aductores: 1 }],
  ['hiperextensiones', 'Hiperextensiones', ['extensiones lumbares', 'back extension'], { lumbar: 1, gluteos: 0.5, isquios: 0.5 }],
  // ---------- gemelos
  ['gemelo_pie', 'Elevación de talones de pie', ['gemelo de pie', 'elevaciones de talón de pie', 'calf raise'], { gemelos: 1 }],
  ['gemelo_sentado', 'Elevación de talones sentado', ['gemelo sentado', 'elevaciones de talón sentado'], { gemelos: 1 }],
  ['gemelo_prensa', 'Gemelo en prensa', [], { gemelos: 1 }],
  // ---------- abdomen
  ['crunch_polea', 'Crunch en polea alta', ['encogimientos en polea alta', 'crunch polea', 'rezo'], { abdomen: 1 }],
  ['crunch', 'Crunch abdominal', ['encogimientos abdominales', 'abdominales'], { abdomen: 1 }],
  ['elev_piernas_colgado', 'Elevaciones de piernas colgado', ['elevaciones de piernas', 'hanging leg raise'], { abdomen: 1 }],
  ['rueda_abdominal', 'Rueda abdominal', ['ab wheel'], { abdomen: 1 }],
  ['plancha', 'Plancha abdominal', ['plancha', 'plank'], { abdomen: 1 }],
  ['pallof', 'Press Pallof', [], { abdomen: 1 }],
];

export const CATALOG = RAW.map(([id, name, aliases, muscles]) => ({ id, name, aliases, muscles, src: 'cat' }));
